[general]
title = "Agent Frameworks"
logo = ""
iconLogo = "emojione-v1:alien-monster"

[general.seo]
name = "Agent Frameworks"
description = "Find the best and newest AI agent frameworks."
url = "https://nuxtstarters.com"

[directory.data]
source = "default" # default, mock, sheets
links = "normal"

# [directory.data.sheets]
# key = "1BKVVFysQT8ZuPY8hUp--jwTrN-U20TrtML0idECIWmc"

[directory.search]
placeholder = "Search among {0} agent frameworks"
showCount = true
icon = "tabler:bow"

[directory.search.tags]
display = "show-all" # options: none,select,show-all
intersection = false

[directory.grid]
list = false
type = ""

[directory.grid.emptyState]
text = "Seems that this entry is missing from the archives."
type = "button"                                              # options: button, simple, link
icon = "tabler:exclamation-mark"

[directory.grid.card]
image = true
border = "shadow" # options: dashed, shadow, outline

[directory.grid.submit]
show = true
first = false
title = "Submit a template"
description = "Submit a template to show off a good project to other people."
hideable = true

[directory.featured]
showOnAllPages = true
showOnSide = true
icon = "tabler:star"
labelForCard = "Featured ✨"

[directory.tagPages]
title = "{0} Frameworks"

[[directory.tags]]
key = "code"
name = "Code Based 👩🏼‍💻"
color = "blue"

[[directory.tags]]
key = "tool"
name = "Tool Use Based 🛠️"
color = "blue"

[[directory.tags]]
key = "visual"
name = "Visual UI 🎨"
color = "green"

[[directory.tags]]
key = "graph"
name = "Graph ⚙️"
color = "green"

[[directory.tags]]
key = "computer"
name = "Computer Use"
color = "green"

[[directory.tags]]
key = "nocode"
name = "No Code"
color = "green"

[[directory.tags]]
key = "mcp"
name = "MCP"
color = "green"

[[directory.tags]]
key = "collaboration"
name = "Multi-Agent 🤝🏽"
color = "green"

[[directory.tags]]
key = "agnostic"
name = "Model Agnostic"
color = "green"

[[directory.tags]]
key = "memory"
name = "Memory 🧠"
color = "green"

[[directory.tags]]
key = "js"
name = "javascript"
color = "indigo"

[[directory.tags]]
key = "py"
name = "python 🐍"
color = "yellow"

[header.banner]
show = true
text = "Brought to your by Mark."
link = "https://x.com/intent/follow?screen_name=mark_builds"
brandText = "AI Agent Frameworks"

[header.navbar]
colorModeSelector = true

[[header.navbar.links]]
name = "Analytics"
href = "https://us.posthog.com/shared/vHlGCcSqPjGH4r_QijaXSETtmN9J-g"
target = "_blank"

[header.actionButton]
text = "Submit a starter"
href = "https://github.com/masterkram/agent-frameworks/pulls"

[footer]
description = "Best directory for my niche."

[footer.socials.github]
link = ""
icon = "tabler:brand-github"

[footer.socials.facebook]
link = ""
icon = "tabler:brand-facebook"

[footer.socials.instagram]
link = ""
icon = "tabler:brand-instagram"

[footer.socials.x]
link = "https://x.com/mark_bruderer"
icon = "tabler:brand-twitter"

[footer.socials.youtube]
link = "https://www.youtube.com/@mark_hacks"
icon = "tabler:brand-youtube"

[ui.icons]
dark = "tabler:moon"
light = "tabler:sun"
